### ISSUE TITLE
Question: Setting classes and different scroll position

### ISSUE THREAD

**Issue by leesherwood** [johnpolacek/superscrollorama#135]
Hopefully this ok to ask here, i couldn't find a reliable source of help for this plugin (help on stackoverflow seems limited for this plugin).

I have two things i'm trying to do, first i need to simply add a class to an element when the element hits the top of the page. No animation or fancyness, just add a class. Is there a way of hooking into the plugins scroll watcher, so rather than using tweenmax, i can just run a simple function. If not, is there a way of doing it at all without having a seperate scrollwatcher for the simple stuff? I tried using TweenMax.set(), but when i use this:

```
    controller.addTween('header', 
            (TweenMax.set('header', {
                className: "static"
            }))
    );
```

It sets the classname immediately on load, i even have the "triggeratcenter" set to true, so i would have expected it to just add the class at the center position.

Following on from that, with the above, i want to add the class when it hits the top of the window, rather than in the center. How do i specify for this specific twen, that it must fire when the element hits the top of the viewport?

Any help would be greatly appreciated

**Comment by prochorz** [comment]
Make like this 
`controller.addTween('.instrument__tabs', TweenMax.to( $('.instrument__tabs'), 0.5, { className: "+=run" } ), 0, 200);`
