### ISSUE TITLE
controller.removeTween on onComplete doesn't work or 

### ISSUE THREAD

**Issue by prBigBrother** [johnpolacek/superscrollorama#151]
Hi! 

Why i can't remove tween, after complete animation? 
```
controller.addTween($('#main-menu'),
                TweenMax.from($('.home-container.weddings article.description'),
                    .5,
                    { 
                        css : {top: 600},
                        onComplete: function(){
                            controller.removeTween($('.home-container.weddings article.description'));
                        }

                    }
                )
            );
```

I't doesn't work. Can you help me? 

I'm need to stop reverse animation for some elements, not to all, then I use .removeTween

Thank you.

**Comment by povtasci** [comment]
Hey guys, can you help me with this issue,
I have code like this, and it doesn't work


    controller.addTween(
        '.fadeSade3',
        TweenMax.from(
            $('.fadeSade3'),
            1.5,
            {
                css:{left:3000},
                onComplete: function() {
                    controller.removeTween($('.fadeSade3'));
                }
            }
        ),
        0,
        -(screen.height)
    );

**Comment by janpaepke** [comment]
Hi there,

without any demo or console errors it's impossible to tell, but I don't think it's necesessary to do this like this.
If you are trying to run an animation only once, you can make use of the 'reverse' option like so:
```js
controller.addTween(
    '.fadeSade3',
    TweenMax.from(
        $('.fadeSade3'),
        1.5,
        {left:3000}
    ),
    0,
    -(screen.height),
    true
);
```

Also please mind, that Superscrollorama has been superseeded by [ScrollMagic](https://github.com/janpaepke/ScrollMagic), which offers the same functionality with more features and better performance.

regards,
J

**Comment by povtasci** [comment]
oh great, thanks @janpaepke ;)
