### ISSUE TITLE
Skip pinned element

### ISSUE THREAD

**Issue by BenjoJ** [johnpolacek/superscrollorama#173]
Hi. This is a really powerful plugin and I am so glad I stumbled across it.

I have a pinned div element which stretches to the size of the screen and has some basic animation in the form of images sliding in as you scroll. 

	controller.pin('#Screen2', 4000, {
		anim: (new TimelineLite())
		  .append([TweenMax.to(jQuery('#img2'), .5, { css: { marginLeft: 0 } })])
		  .append([TweenMax.to(jQuery('#img3'), .5, { css: { marginLeft: 0 } })])
		  .append([TweenMax.to(jQuery('#img4'), .5, { css: { marginLeft: 0 } })])
	}, 2000);

At the bottom of this "Screen2" element I have a button which fires a scroll event, so the user can skip down to the next screen.

	var offset = jQuery("#Screen3").offset();
	jQuery("html,body").animate({
		scrollTop: offset.top,
		scrollLeft: offset.left
	}, 1000, 'easeOutQuart');

The problem I have is I do not want the animations in the pinned element to fire when the above scroll function is fired. I want it to just scroll to that element smoothly. What happens is that all the elements in the tween animation fire in one by one and when they have finished, the page scrolls to the desired element.

I have tried using the removePin function, but this disables the pin completely after you have scrolled. I tried firing the controller.pin function again after the scroll event has finished, but this causes the screen to jump back up to the pinned element (Screen2).

Is there anything I can do to get around this please?

Thanks

Ben

**Comment by janpaepke** [comment]
Hi Ben!

Glad you like the plugin.
Superscrollorama has ben superseded by [ScrollMagic](https://github.com/janpaepke/ScrollMagic).
The logic is quite similar and I'm sure you'll have an easy time refactoring your code to ScrollMagic.

If you did you can make use of ScrollMagic's "enabled" method to temporarily disable the animations from happening: http://janpaepke.github.io/ScrollMagic/docs/ScrollMagic.Scene.html#enabled

Should you have any problems moving to ScrollMagic or implementing this, please follow [ScrollMagic's troubleshooting guide](https://github.com/janpaepke/ScrollMagic/blob/master/CONTRIBUTING.md#troubleshooting) and/or [post an issue](https://github.com/janpaepke/ScrollMagic/issues).

best regards,
Jan

**Comment by BenjoJ** [comment]
Ah, perfect thanks. I'll give it a go.

**Comment by BenjoJ** [comment]
The documentation for ScrollMagic isn't very good. Trying to achieve what I did with Scrollorama seems a bit cumbersome, having to create scene objects for each of the objects I want to slide in. This doesn't seem right to me but there is nowhere in your documentation that I can find a relevant example, as most of it is spinning a single object around. If you can point me in the right direction I would appreciate it, as the code below is super glitchy and the slides jump all over the place and don't go back to where they were when you scroll back up..

	var pin = new ScrollMagic.Scene({ triggerElement: "#Screen2", duration: jQuery(window).height() * 2})
						.setPin("#Screen2", { pushFollowers: true })
						.addTo(controller);

	var scene = new ScrollMagic.Scene({ triggerElement: "#Screen2", duration: iScreenSize })
						.setTween(TweenMax.to("#img2", 1, { marginLeft: 0, ease: Linear.easeNone }))
						.addTo(controller);

	var scene2 = new ScrollMagic.Scene({ triggerElement: "#img2", duration: iScreenSize })
						.setTween(TweenMax.to("#img3", 1, { marginLeft: 0, ease: Linear.easeNone }))
						.addTo(controller);

http://janpaepke.github.io/ScrollMagic/examples/basic/simple_tweening.html

I have looked through these.

**Comment by BenjoJ** [comment]
The pin animations also start when the pinned element is half way up the screen, not when it reaches the top, and I can't find anything in your documentation that explains how to change this.

**Comment by BenjoJ** [comment]
Hi Jan

I am using the 'enabled' method, but it appears to only work the first time I am using it. When the function below is called for the first time, it does indeed disable the scene. However, from then on, calling this function does not seem to disable the scene. Am I doing something incorrectly here?

function scrollToEl(sID) {
	if (jQuery(sID).length) {
		PhilosophyScene.enabled(false);
		var offset = jQuery(sID).offset();
		jQuery("html,body").animate({
			scrollTop: offset.top - 0,
			scrollLeft: offset.left
		}, 1000, 'easeOutQuart', function () { PhilosophyScene.enabled(true) });
	}

}

Thanks for your continued support.

Ben

**Comment by janpaepke** [comment]
It looks like ScrollMagic code.
Please repost it in ScrollMagic support and try to give more context. A jsfiddle if possible.
