### ISSUE TITLE
Is there a seek functionality ? 

### ISSUE THREAD

**Issue by pravin-d** [johnpolacek/superscrollorama#174]
TimelineMax has  a function called seek() to skip to some any animation at random

**Comment by janpaepke** [comment]
Note, that support for Superscrollorama has been suspended, as it has been superseded by [ScrollMagic](https://github.com/janpaepke/ScrollMagic).
But what you're probably looking fore is a simple `window.scrollTo(x, y)` with `x` being 0 and `y` being your target "seek" position.
