### ISSUE TITLE
add package.json

### ISSUE THREAD

**Issue by maruilian11** [johnpolacek/superscrollorama#178]
would you please consider adding package.json so that we can add your lib on https://cdnjs.com.
thank you very much!
https://github.com/cdnjs/cdnjs/issues/5924

**Comment by jkrot** [comment]
The authors view is that this plugin is deprecated, see https://github.com/janpaepke/ScrollMagic for the newest version.

**Comment by johnpolacek** [comment]
Thanks jkrot - yes that's what I would advise.

**Comment by maruilian11** [comment]
ok, thank you.
